title: Intro to JavaScript
description: >-
    Course description: Place your course description here...
template:
    name: learninglab-template
    repo: your-learninglab-template
before:
    - type: createIssue
      title: Week 1
      body: 1.1-Week 1 Step 1.md
steps:
    - title: 'Week 1: Week 1 Step 1'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.2-Week 1 Step 2.md
          files: ['notes.md']
    - title: 'Week 1: Week 1 Step 2'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.3-Week 1 Step 3.md
          files: ['notes.md']
    - title: 'Week 1: Week 1 Step 3'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.4-Week 1 Step 4.md
          files: ['notes.md', 'promise.js']
    - title: 'Week 1: Week 1 Step 4'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.5-Week 1 Step 5.md
          files: ['notes.md']
    - title: 'Week 1: Week 1 Step 5'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.6-Week 1 Step 6.md
          files: ['notes.md', 'app.js']
    - title: 'Week 1: Week 1 Step 6'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.7-Week 1 Step 7.md
          files: ['notes.md', '.env', '.gitignore', 'app.js']
    - title: 'Week 1: Week 1 Step 7'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.8-Week 1 Step 8.md
          files: ['app.js']
    - title: 'Week 1: Week 1 Step 8'
      description: Description:
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          files: ['app.js']
    - title: 'Week 1: Feedback'
      description: Provide your feedback for Week 1!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1-complete.md
        - type: closeIssue
